config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :cars, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:index, :create]
  end

  resources :bookings, only: [:index, :update]

  namespace :owner do
    resources :bookings, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  enum status: { pending: 0, accepted: 1, declined: 2 }
  validates :status, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  def pending?
    status == 'pending'
  end

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  validates :brand, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :rate, presence: true

  include PgSearch::Model

  pg_search_scope :search_by,
    against: [:brand, :model, :year],
    associated_against: {
      user: [:address]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def parsed_description
    JSON.parse(description)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :cars
  has_many :bookings_as_owner, through: :cars, source: :bookings
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def index
    @bookings = current_user.bookings.order(start_date: :desc)
  end

  def create
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.car = @car
    days = (@booking.end_date - @booking.start_date).to_i
    @booking.total_price = days * @car.rate
    @booking.user = current_user
    if @booking.save

      redirect_to bookings_path, notice: "Booking was successfully created"
    else

      # show the form again but with the @restaurant in this method
      render 'cars/show', status: :unprocessable_entity
    end
  end


  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      # redirect_to # up to you...
      redirect_to owner_bookings_path, notice: "Booking was successfully reviewed"
    else
      # render # where was the booking update form?
      render 'owner/bookings', status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id, :status)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:query].present?
      @cars = Car.search_by(params[:query])
    else
      @cars = Car.all
    end
    @cars_for_markers = Car.all
    @markers = @cars_for_markers.map do |car|
      {
        lat: car.user.latitude,
        lng: car.user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { car: car }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    lat = @car.user.latitude
    lng = @car.user.longitude
    @markers = [{
      lat: lat,
      lng: lng,
      info_window_html: render_to_string(partial: "info_window", locals: { car: @car }),
      marker_html: render_to_string(partial: "marker")
      }]
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to owner_bookings_path, notice: "Car was successfully listed"
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def car_params
    params.required(:car).permit(:brand, :model, :year, :rate, :description, photos: [])
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  before_action :authenticate_user!
  def index
    @bookings_owner = current_user.bookings_as_owner
    @bookings_user = current_user.bookings.order(start_date: :desc)
    @cars = current_user.cars
  end

  def create
    @car = Car.new(car_params)
    @car.owner = current_owner

    if @car.save
      redirect_to owner_bookings_path, notice: 'Car was successfully added.'
    else
      render :new
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container mt-5">
  <div class="row">
    <h1>Your bookings</h1>
  </div>

</div>

<div class="container mt-5 pad-bottom">
    <div class="cards-booking">
    <% @bookings.each do |booking| %>
      <%= render 'shared/card_booking', booking: booking %>
    <% end %>
  </div>
</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/cars/_info_window.html.erb
<h4><%= link_to car.brand, car_path(car), class: 'text-decoration-none link-dark' %></h4>
<p><%= car.model %></p>
<p><i class="fa-solid fa-map-pin"></i> <%= car.user.address %></p>

app/views/cars/_marker.html.erb
<%= image_tag "car.png", height: 30, width: 50, alt: "Logo" %>

app/views/cars/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="d-flex justify-content-between">
      <h1>Showing result</h1>
    </div>
  </div>
</div>

<div class="container mt-5 pad-bottom">
  <div class="cards">
    <% @cars.each do |car| %>
      <%= render 'shared/card', car: car %>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="d-flex justify-content-center align-items-center min-vh-100">
  <div class="card p-4" style="max-width: 600px; width: 100%;">
    <h1 class="text-center mb-4">Add a Car</h1>
    <%= simple_form_for @car do |form| %>
      <div class="mb-3">
        <%= form.input :brand, input_html: { class: 'form-control' } %>
      </div>
      <div class="mb-3">
        <%= form.input :model, input_html: { class: 'form-control' } %>
      </div>
      <div class="mb-3">
        <%= form.input :year, input_html: { class: 'form-control' } %>
      </div>
      <div class="mb-3">
        <%= form.input :rate, input_html: { class: 'form-control' } %>
      </div>
      <div class="mb-3">
        <%= form.input :description, input_html: { class: 'form-control' } %>
      </div>
      <div class="mb-3">
        <%= form.input :photos, as: :file, input_html: { class: 'form-control', multiple: true } %>
      </div>
      <div class="d-grid">
        <%= form.submit "Create Listing", class: 'create-form-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container pad-bottom">
  <div class="row">
    <div class="car-grid" style="margin-top: 20px;">
      <div class="main">
        <%= cl_image_tag @car.photos.first.key, 
        height: 700, 
        width: 1300, 
        crop: :fill, 
        fetch_format: :auto, 
        quality: :auto, 
        style:'', 
        class: "main image-item" %>
      </div>
      <% @car.photos.each_with_index do |photo, index| %>
        <% if index > 0 %>
          <%= cl_image_tag photo.key, 
          height: 300, 
          width: 400, 
          crop: :fill, 
          fetch_format: :auto, 
          quality: :auto, 
          style:'', 
          class: "item#{index} image-item" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-7">
      <div class="card-car">
        <div class="card-car-infos">
          <div class="d-flex justify-content-between">
            <h2><strong><%= @car.brand%> <%= @car.model %></strong></h2>
            <h5><strong>$<%= @car.rate %>0</strong> /day</h5>
          </div>
          <h5><%= @car.user.address %></h5>
          <div class="mt-3">
            <% description = @car.parsed_description.each do |line|%>
              <p><%= line  %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-5">
      <div data-controller="booking-price" data-booking-price-rate-value="<%= @car.rate %>">
        <div class="cards-form">
          <p class='fw-bold fs-3'>$<%= @car.rate %>0 <small class='fw-light'>/day</small></p>
          <%= simple_form_for [@car, @booking] do |f| %>
            <div class="d-flex">
              <%= f.input :start_date, html5: true, input_html: { data: { booking_price_target: 'start_date', action: 'change->booking-price#update' }, min: Date.today } %>
              <%= f.input :end_date, html5: true, input_html: { data: { booking_price_target: 'end_date', action: 'change->booking-price#update' }, min: Date.today } %>
            </div>
            <%= f.submit 'Book', class: 'create-form-button w-100' %>
            <p class='mt-3 d-flex align-items-center justify-content-between'>
              <span data-booking-price-target='info'></span>
              <span class='fw-bold' data-booking-price-target='rate'></span>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%# map starts here %>
  <div class="showmap" style="width: 100%; height: 500px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="container mt-5">
  <div class="row">
    <h1>Owners Bookings to Review</h1>
    <%= link_to "List your car", new_car_path, class: "create-button m-1 p-2 border rounded-pill shadow-sm btn btn-light align-item-center" %>
  </div>
</div>
<div class="container mt-5 pad-bottom">
  <div class="cards-booking">
    <% @bookings_owner.each do |booking| %>
      <%= render 'shared/card_booking_owner', booking: booking %>
    <% end %>
  </div>
</div>
<div class="container mt-5 pb-2 pad-bottom">
<h2>Your Cars</h2>
  <div class="cards">
    <% @cars.each do |car| %>
      <%= render 'shared/card', car: car %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://images.pexels.com/photos/6462662/pexels-photo-6462662.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <h1><strong><i>T U R B O</i></strong></h1>
        <h4>Rent your dream car today!</h4>
        <%# <p>See our Lamborghini listings</p> %>
        <%= link_to 'See our Lamborghini listings', cars_path(query: 'lamborghini'), class: "m-1 p-2 border rounded-pill shadow-sm btn btn-light align-item-center" %>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://www.jornaldosclassicos.com/wp-content/uploads/2023/02/Header_BugattiChironProfilee.jpg" class="d-block w-100" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
        <h1><strong><i>T U R B O</i></strong></h1>
        <h2>Rent your dream car today!</h2>
        <%# <p>Some representative placeholder content for the second slide.</p> %>
        <%= link_to 'See our Bugatti listings', cars_path(query: 'bugatti'), class: "m-1 p-2 border rounded-pill shadow-sm btn btn-light align-item-center" %>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.pinimg.com/originals/48/43/bd/4843bd166ae7e36364292a25c712736d.jpg" class="d-block w-100" alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
        <h1><strong><i>T U R B O</i></strong></h1>
        <h2>Rent your dream car today!</h2>
        <%# <p>Some representative placeholder content for the third slide.</p> %>
        <%= link_to 'See our McLaren listings', cars_path(query: 'mclaren'), class: "m-1 p-2 border rounded-pill shadow-sm btn btn-light align-item-center" %>
      </div>


    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_card.html.erb
<%= link_to car_path(car), class:"text-decoration-none link-dark" do %>
  <div class="card-car">
    <% if car.photos.attached? %>
      <%= cl_image_tag car.photos.first.key, 
        height: 300, 
        width: 400, 
        crop: :fill, 
        fetch_format: :auto,  # Enables automatic format selection (f_auto)
        quality: :auto         # Enables automatic quality optimization (q_auto)
      %>
    <% else %>
      <%= image_tag "https://images.pexels.com/photos/6462662/pexels-photo-6462662.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2", height: 300, width: 400 %>
    <% end %>
    <div class="card-car-infos">
      <div class="d-flex justify-content-between align-items-top">
        <h2><strong><%= car.brand%></strong> <%= car.model %></h2>
        <h4><strong>$<%= car.rate %></strong><span class="text-grey">/day</span></h4>
      </div>
      <h6 class="mt-1"><i class="fa-solid fa-map-pin"></i> <%= car.user.address %> | <%= car.year %></h6>
      <div class="mt-3">
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_card_booking.html.erb
<div class="card-booking">
  <%= cl_image_tag booking.car.photos.first.key, height: 300, width: 400, crop: :fill, class: "border border-white border-2" %>
  <div class="card-booking-infos p-3 d-flex-column align-items-stretch">
      <div class="d-flex justify-content-between align-items-center">
        <h5><strong><%= booking.start_date.strftime("%b %e") %> to <%= booking.end_date.strftime("%b %d, %Y") %> </strong> </h5>
        <div class="badge rounded-pill status-<%= booking.status %>"> <div> <%= booking.status.capitalize %> </div> </div>
      </div>
      <div>
        <h5 class="p-0"><%= booking.car.brand %> <%= booking.car.model %></h3>
        <p class="p-0">Owner: <strong><%= booking.car.user.first_name %> <%= booking.car.user.last_name %></strong> </p>
</div>
      <div class="d-flex justify-content-between align-items-center">
        <h5>$<%= booking.car.rate %>0 per day</h5>
        <h5><strong>Total $<%= booking.total_price %>0 </strong></h5>
      </div>
  </div>
</div>

app/views/shared/_card_booking_owner.html.erb
<div class="card-booking">
  <%= cl_image_tag booking.car.photos.first.key, 
  height: 300, 
  width: 400, 
  crop: :fill, 
  fetch_format: :auto,  # Enables automatic format selection (f_auto)
  quality: :auto         # Enables automatic quality optimization (q_auto)
  class: "border border-white border-2" %>
  <div class="card-booking-infos p-3 d-flex-column align-items-stretch">
      <div class="d-flex justify-content-between align-items-center">
        <h5><strong><%= booking.start_date.strftime("%b %e") %> to <%= booking.end_date.strftime("%b %d, %Y") %> </strong> </h5>

        <% if booking.pending? %>
          <div class="booking-actions">
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'accepted' } %>
              <%= f.submit 'Accept', class: 'btn-custom btn-accept' %>
            <% end %>
            <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: { value: 'declined' } %>
              <%= f.submit 'Decline', class: 'btn-custom btn-decline' %>
            <% end %>
          </div>
        <% else %>
          <div class="badge rounded-pill status-<%= booking.status %>"> <div> <%= booking.status.capitalize %> </div> </div>
        <% end %>


      </div>
      <div>
        <h5 class="p-0"><%= booking.car.brand %> <%= booking.car.model %></h3>
        <p class="p-0">Owner: <strong><%= booking.car.user.first_name %> <%= booking.car.user.last_name %></strong> </p>
</div>
      <div class="d-flex justify-content-between align-items-center">
        <h5>$<%= booking.car.rate %>0 per day</h5>
        <h5><strong>$<%= booking.total_price %>0 </strong></h5>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon align-items-center py-0">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" style="flex: 1">
      <%= link_to "TURBO", "/", class: "navbar-brand text-white p-3"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav align-items-center me-auto">
        <li class="nav-item active p-3">
          <%= link_to "All cars", "/cars", class: "text-decoration-none text-white align-item-center" %>
        </li>
        <li class="nav-item p-3 text-decoration-none text-white align-item-center" type="link" data-insert-review-target='link' data-bs-toggle="collapse" data-bs-target="#reviewCreate" aria-expanded="false" aria-controls="reviewCreate">
          <%= link_to "Brands", "/cars", class: "text-decoration-none text-white align-item-center" %></li>
        <li class="nav-item p-3 text-decoration-none text-white align-item-center" type="link" data-insert-review-target='link' data-bs-toggle="collapse" data-bs-target="#reviewLocation" aria-expanded="false" aria-controls="reviewLocation">
          <%= link_to "Locations", "/cars", class: "text-decoration-none text-white align-item-center" %>
        </li>
      </ul>
    </div>
    <div style="flex: 1" >
      <div class="row">
        <%= form_with url: cars_path, method: :get, class: "d-flex align-items-center" do %>
          <h6 class="pt-1 m-2"><i class="fa-solid fa-magnifying-glass text-white"></i></h6>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control rounded-pill",
            placeholder: "Search by city, brand, model, or year"
            %>
          <%= submit_tag "Search", name: "", class: "m-3 btn btn-light shadow-sm align-item-center border rounded-pill" %>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse justify-content-end" style="flex: 1" id="navbarSupportedContent">
      <span class="nav-item active p-3">
        <%= link_to "Switch to owner", owner_bookings_path, class: "text-decoration-none text-white align-item-center" %>
      </span>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "See my bookings", "/bookings/", class: "dropdown-item text-secondary" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-secondary" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="collapse" id="reviewCreate">
    <div class="d-flex justify-content-center mt-auto">
      <%= link_to cars_path + "?query=lamborghini", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtuhjb7P7sl7uoYaoa0Rd9DSfWF_xD9OfKcA&s" class="logo">
          <%# <h6>Lamborghini</h6> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=bugatti", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://i.pinimg.com/736x/b3/51/fb/b351fb832347519de9172498d7439992.jpg" class="logo">
          <%# <p>Bugatti</p> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=mclaren", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://ih1.redbubble.net/image.2473501157.0467/flat,750x,075,f-pad,750x1000,f8f8f8.jpg" class="logo">
          <%# <p>McLaren</p> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=ferrari", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://i.pinimg.com/564x/1f/d0/7e/1fd07e1786e734eea0a974cf90080861.jpg" class="logo">
          <%# <p>Ferrari</p> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=rollsroyce", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://i.ebayimg.com/images/g/0GwAAOSwvbJj3s6L/s-l1200.jpg" class="logo">
          <%# <p>Rolls Royce</p> %>
        </div>
      <% end %>
    </div>

    <div class="d-flex justify-content-center mb-auto">
      <%= link_to cars_path + "?query=porsche", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://imagenes.elpais.com/resizer/v2/JLYOR4AIRNFTVOJMWI7G6BLZTU.jpg?auth=29657c259ddf29903d02b1211376c3143d39a9759f162384d20f124776a3ed53&width=1200" class="logo">
          <%# <p>Porsche</p> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=aston martin", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://cdn.worldvectorlogo.com/logos/aston-martin.svg" class="logo">
          <%# <p>Mercedes-Benz</p> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=alpha romeo", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://www.shutterstock.com/image-vector/chattogram-bangladesh-november-08-2023-600nw-2385417383.jpg" class="logo">
          <%# <p>Alfa Romeo</p> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=mercedes", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://i.pinimg.com/736x/2b/8f/0c/2b8f0c2ffdcb7a2299ba30a61e8d9111.jpg" class="logo">
          <%# <p>Mercedes-Benz</p> %>
        </div>
      <% end %>
      <%= link_to cars_path + "?query=nissan", class:"text-decoration-none link-dark m-3" do %>
        <div>
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTutG4fdc14QZjkIDM80eXyopDyYkatioIy7w&s" class="logo">
          <%# <p>Nissan</p> %>
        </div>
      <% end %>
    </div>

  </div>
</div>

<div class="collapse" id="reviewLocation">
  <div>
    <div class="d-flex justify-content-center mt-auto">
      <%= link_to 'Tokyo', cars_path + "?query=tokyo", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
      <%= link_to 'Sapporo', cars_path + "?query=sapporo", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
      <%= link_to 'Fukuoka', cars_path + "?query=fukuoka", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
      <%= link_to 'Osaka', cars_path + "?query=osaka", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
    </div>

    <div class="d-flex justify-content-center mb-auto">
      <%= link_to 'Kyoto', cars_path + "?query=kyoto", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
      <%= link_to 'Sendai', cars_path + "?query=sendai", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
      <%= link_to 'Saitama', cars_path + "?query=saitama", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
      <%= link_to 'Kobe', cars_path + "?query=kobe", class: "m-1 p-2 text-decoration-none link-dark align-item-center"%>
    </div>
  </div>
</div>

<div class="collapse" id="reviewSearch">
</div>